baseurl = "http://replace-this-with-your-domain.com/"
languageCode = "en-us"
title = "Type theme"
theme = "hugo-type-theme"
# Enable comments by entering your Disqus shortname
disqusShortname = "spf13"
# Add your tracking code to enable Google Analytics
googleAnalytics = ""
# Posts per page
paginate = 10


[params]
	author = "Your name"
	description = "Add a description of your website"
	# Either show custom avatar on the top
	# left by adding the filename in below
	avatar = "img/avatar.png"
	# or use Gravatar by adding your email address to generate a unique avatar
	gravatar = "your@email.com"

	headerText = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.<br><br>Remove all header text in **config.toml** to disable this feature."
	# To add a header background to the main site, save your image under static/img/.
	# If now image path is provided, a orange background will be shown instead.
	headerImage = ""
	copyright = "Released under the MIT license<br>Powered by [Hugo](//gohugo.io/) with the [Type Theme](//github.com/digitalcraftsman/hugo-type-theme)"


	[params.social]
		# Insert your accout name and the icon will be shown in the right menu
		rss = true
		homepage = true
		email = "hello@example.com"
		behance = ""
		bitbucket  =""
		dribbble = ""
		facebook = ""
		flickr = ""
		github = "digitalcraftsman/hugo-type-theme"
		googleplus = ""
		instagram = ""
		linkedin = ""
		pinterest = ""
		reddit = ""
		soundcloud = ""
		stackexchange = ""
		steam = ""
		tumblr = ""
		twitter = ""
		wordpress = ""
		youtube = ""
